### PR TITLE
Remove StaticReflectionService

### PR DESCRIPTION
**Pull request by greg0ire**
Additionally, implementations of ReflectionService may no longer return null for calls to `getClass()`.

### CODE REVIEW

**Comment by greg0ire** [comment]
I am tempted to make `ReflectionService` a class, and have `RuntimeReflectionService` extend it and be deprecated in favor of it, or even be removed. Thoughts?

**Comment by SenseException** [comment]
Because `RuntimeReflectionService` is the last class implementing `ReflectionService`? Is the goal to have just one implementation for a `ReflectionService`?

**Comment by greg0ire** [comment]
Yeah, AFAIK it's the sole implementation of `ReflectionService`, so I'm not sure if there is still a point in having `ReflectionService` be an interface.

**Review by alcaeus — APPROVED** [review]
LGTM. Converting `ReflectionService` to a class is going to be a tough to manage BC break - I don't think it's worth it.

**Pull request merged**
