### PR TITLE
Decouple RuntimePublicReflectionProperty::getValue() from Doctrine\Common\Proxy\Proxy

### PR DESCRIPTION
**Pull request by nicolas-grekas**
On the path to decoupling from doctrine/common
Somewhat related to #299

### CODE REVIEW

**Comment by greg0ire** [comment]
Nice trick! I'd update the PR to remove now useless Phpstan ignore rules, but I'm on my phone.

**Review by greg0ire — APPROVED** [review]
Quite excited about rebasing #299 after this gets merged :) That circular dependency has been a pain.

**Review by malarzm — APPROVED** [review]
This is awesome!

**Comment by greg0ire** [comment]
Thanks @nicolas-grekas !

**Pull request merged**
