### PR TITLE
Improve the ACMF::doLoadMetadata docblock

### PR DESCRIPTION
**Pull request by mpdude**

### CODE REVIEW

**Comment by derrabus** [comment]
PHPCS fails. 🙂

**Comment by mpdude** [comment]
Why can’t it just automatically commit the necessary fixes?

**Comment by derrabus** [comment]
🤷🏻‍♂️

**Comment by greg0ire** [comment]
Hey why don't you use a `pre-push` hook instead of blaming our beautiful pipeline? It will be useful for other commands that can't be autofixed, and will be better for the planet in cases where phpcs is not the only failing job:

```bash
#!/bin/bash
set -e
echo ''|vendor/bin/phpcs
vendor/bin/phpstan
vendor/bin/psalm
vendor/bin/phpunit
```

**Review by greg0ire — APPROVED** [review]

**Pull request merged**
