### PR TITLE
Drop backwards-compatibility layer

### PR DESCRIPTION
**Pull request by greg0ire**
Draft PR because I don't actually want to get this merged, this is just to show what the diff with 1.4.x is, and to (hopefully) get a green build. If this looks ok, then we could move 2.x to 3.x, and this branch to 2.x

### CODE REVIEW

**Comment by greg0ire** [comment]
A quick grep shows that this is very far from complete :sweat_smile:

**Comment by greg0ire** [comment]
It also shows that another PR needs to be done to update the docs: they still refer to the outdated namespace.

**Comment by greg0ire** [comment]
Regarding the docs, see https://github.com/doctrine/persistence/pull/107

**Comment by alcaeus** [comment]
> If this looks ok, then we could move 2.x to 3.x, and this branch to 2.x

Note sure if that's necessary. IMO, the following works fine:
* 1.3.x: Introduces new API and uses `@deprecated` annotations on deprecated code paths
* 1.4.x: Keeps new API, introduces `@trigger_error` calls to announce deprecations loudly
* 2.0.x: Drops legacy API, introduces parameter types (as those are ok to be removed when inheriting). Documentation informs people to add return types to inherited methods
* 3.0.x: Introduces return types to all methods

**Comment by greg0ire** [comment]
My main point with this PR is that I don't touch dependencies version constraints, including and especially the php one, and that's what would make bumping to 2.0 and dropping the `*_exists` calls from the ORM (for instance) acceptable.

**Comment by alcaeus** [comment]
Ah, I see. So we'd be postponing the argument types to 3.0 to avoid dropping PHP 7.2 in 2.0, because that would make it ineligible for ORM 2.7? My head is spinning, but I think I understood.

**Comment by greg0ire** [comment]
Yes, that's exactly my point. Note that it indeed means postponing argument types to 3.0, but that 3.0 can and should still happen very soon IMO. It's just that there would be an easier-to-upgrade-to intermediary step.

**Comment by alcaeus** [comment]
If it makes upgrading ORM easier, sure :)

**Comment by greg0ire** [comment]
I pushed this as 2.0.x :)

**Pull request closed without merging**
