### PR TITLE
Use a shallower tree

### PR DESCRIPTION
**Pull request by greg0ire**
It makes it easier to work with fuzzy matchers.
I'm targeting the lowest supported branch because otherwise some operations might be painful, like switching branches on Github while browsing a file, or performing a merge up in some situation.

I'll take care of merging this up.

### CODE REVIEW

**Review by SenseException — DISMISSED** [review]
Technically okay, but where is fuzzy matching used that it affects the changes?

**Comment by greg0ire** [comment]
> Technically okay, but where is fuzzy matching used that it affects the changes?

You mean that it is affected by the changes? [Fuzzy matching is used in IDEs](https://github.com/nvim-telescope/telescope.nvim) and works best in my experience when file paths are short and not repetitive.

**Comment by derrabus** [comment]
I'd feel more comfortable merging this to 2.4.x, tbh. This is certainly not a bugfix.

**Comment by greg0ire** [comment]
@derrabus OK, I'll retarget. It might be cumbersome for a while, but 2.3.x isn't going to live very long.

**Comment by derrabus** [comment]
Let's finish the other work planned for 2.4 first an then rebase an merge this PR.

**Review by malarzm — DISMISSED** [review]

**Comment by greg0ire** [comment]
I think 2.4.0 should be released, so let's revive this?

**Review by SenseException — APPROVED** [review]

**Pull request merged**
