### PR TITLE
Add class-string typehint for getAssociationTargetClass

### PR DESCRIPTION
**Pull request by VincentLanglet**

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Friendly ping @greg0ire :)

**Comment by greg0ire** [comment]
:thinking: why are you targeting 2.1.x ?

**Comment by VincentLanglet** [comment]
> 🤔 why are you targeting 2.1.x ?

It was the default branch, and I don't know the rules about the phpdoc.
It can be considered as a patch, because it will fix some developper psalm issues.

You prefer 2.2.x ?

**Comment by greg0ire** [comment]
I think 2.2.x is appropriate indeed 👍 . Your proposal is more precise, but `string` was not wrong either.

**Comment by VincentLanglet** [comment]
Done

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @VincentLanglet !

**Pull request merged**
