### PR TITLE
Stop using ObjectManagerAware in tests

### PR DESCRIPTION
**Pull request by greg0ire**
It also seems some tests were invalid: ObjectManagerAware was used to
avoid creating a custom Proxy interface but really is not. TestObject is
not a proxy, and should not implement it.

To understand this, I found a commit but no pull request in this repository, then I remembered this repository was split from another, so here it is: https://github.com/doctrine/common/pull/387

### CODE REVIEW

**Comment by greg0ire** [comment]
I'm not sure if this is the correct thing to do, so I'd like to summon some help in untangling this:

- @Ocramius and @enumag because of the `doctrine/common` PR
- @lcobucci because of 7538983699183d79dc2854953609359b2c934008, which introduced the calls to `assertNull()`
- @phansys because of f045d3cf58b48008ef997a9f287641ecf9c52c86, which introduced a test without assertions.

**Comment by lcobucci** [comment]
@greg0ire I vaguely remember debugging this... I think the assertions were added because that was the return back then (it's been a while, though)

**Comment by greg0ire** [comment]
Ok, then it's probably fine to remove them.

**Review by derrabus — APPROVED** [review]

**Comment by lcobucci** [comment]
I'd use different a approach for checking that (`addToAssertionCount` or something), though. That annotation makes phpunit ignore the test coverage - which influences mutation tests.

**Pull request merged**
