### PR TITLE
Allow PHP 8

### PR DESCRIPTION
**Pull request by greg0ire**
We want to let other projects experiment and report bugs to us. Failure
is allowed for now and should no longer be after the feature freeze
starts.

### CODE REVIEW

**Comment by greg0ire** [comment]
@alcaeus not 100% sure about this one: will we be able to fix these failures w/o a BC break?

https://travis-ci.org/github/doctrine/persistence/jobs/691455511

**Comment by alcaeus** [comment]
> @alcaeus not 100% sure about this one: will we be able to fix these failures w/o a BC break?
> 
> https://travis-ci.org/github/doctrine/persistence/jobs/691455511

I'd have to take a look, but `ReflectionParameter::getType` should be what we're looking for.

**Comment by greg0ire** [comment]
Ok, I'm going to push a commit with PHPunit `8 || 9` in case it's just that.

**Comment by greg0ire** [comment]
Still fails, but far better now.

**Comment by greg0ire** [comment]
All good :)

**Review by SenseException — APPROVED** [review]

**Review by alcaeus — APPROVED** [review]

**Comment by esbobkov** [comment]
Hello!

Could you tag this?)

**Comment by greg0ire** [comment]
@esbobkov done!

**Comment by GPHemsley** [comment]
It looks like this could use a 2.0.x release, too? (1.4.x has never been released?)

**Pull request merged**
