### PR TITLE
Bump PHPStan and Psalm

### PR DESCRIPTION
**Pull request by drupol**

### CODE REVIEW

**Comment by stof** [comment]
IIRC, using fixed versions rather than a range was meant to avoid getting new violations reported randomly in PRs not related to upgrading phpstan or psalm due to the CI picking a new version silently.

**Comment by drupol** [comment]
Ok! I will amend.

Had to run away, but will fix this asap before lunch

**Comment by drupol** [comment]
Done, I updated the classes where the parameter name was not matching the interface. I did not modified the interfaces in order to avoid breaking stuff in some other external projects.

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @drupol !

**Comment by drupol** [comment]
Merci :)

**Pull request merged**
