### PR TITLE
Migrate all checks to Github Actions

### PR DESCRIPTION
**Pull request by greg0ire**
It is faster, we get more precise feedback right in Github's UI, and we
can reuse common workflows.

### CODE REVIEW

**Comment by greg0ire** [comment]
Blocked by #133

**Comment by greg0ire** [comment]
Also, I need to use `composer update`, not `composer install` otherwise I will not be able to test 7.1 and 8.0

**Comment by greg0ire** [comment]
Rebasing on 2.1.x should help, since there is no requirement on `doctrine/reflection` there.

**Comment by greg0ire** [comment]
When this is approved, I will change the settings so this is mergeable and new jobs are required.

**Review by ostrolucky — APPROVED** [review]

**Pull request merged**
