### PR TITLE
Remove PersistentObject magic object.

### PR DESCRIPTION
**Pull request by jwage**
PersistentObject was initially introduced to show that you can do ActiveRecord with Doctrine components.

Its usage has never been endorsed, and objects "saving themselves" are mostly an idea that is better implemented in other tools that focus just on that, while the Doctrine organization mostly focuses on mappers.

If somebody needs this, it will be trivial for them to re-implement this in their own domain, but we shouldn't push it forward from our end.

PR to deprecate this functionality in 1.2 first can be found here https://github.com/doctrine/persistence/pull/55

### CODE REVIEW

**Comment by ostrolucky** [comment]
"Why" is needed

**Comment by Ocramius** [comment]
@ostrolucky here's my attempt to clear up the "why":

`PersistentObject` was initially designed as a stunt by @beberlei to show that "yes, you can do ActiveRecord even with Doctrine components".

Its usage has never been endorsed, and objects "saving themselves" are mostly an idea that is better implemented in other tools that focus just on that, while the Doctrine organisation mostly focuses on mappers.

If somebody needs this, it will be trivial for them to re-implement this in their own domain, but we shouldn't push it forward from our end.

**Comment by ostrolucky** [comment]
Thanks, that's all everybody out of the loop needs

**Comment by jwage** [comment]
@ostrolucky PR to add deprecation to 1.2 here https://github.com/doctrine/persistence/pull/55

**Pull request merged**
